### PR TITLE
generate_more_and_faster

### PR DESCRIPTION
**Pull request by CrimsonFreak**
Let me know if you want me to provide some examples of what I mean by "filtering from the mega file"
I plan on extensively using this file in the upcoming weeks, so I'll probably publish that work anyways.

### CODE REVIEW

**Comment by CrimsonFreak** [comment]
I've created another file to get all the data from the starmap (not filtered) way faster.
I haven't created any package script to run this one

**Comment by ari-party** [comment]
The Starmap API has a rate limit. + Sending tens/hundreds of HTTP requests is unconventional.

**Comment by ari-party** [comment]
Probably rewriting into typescript.

**Comment by CrimsonFreak** [comment]
> The Starmap API has a rate limit. + Sending tens/hundreds of HTTP requests is unconventional.

Promise.all is what you're looking for

**Pull request closed without merging**
